NAME: "FastGPT"
VERSION: "v0.0.1"
DESC: "接入FastGPT应用"
META: {
  official: "https://fastgpt.cn",
  configuration: "FastGPT云服务: https://cloud.fastgpt.cn",
  tips: "",
  fee: ""
}
# 暴露给前端的参数选项以及默认值
PARAMETERS: [
  {
    name: "base_url",
    description: "FastGPT base url.",
    type: "string",
    required: false,
    choices: [],
    default: ""
  },
  {
    name: "api_key",
    description: "FastGPT API Key.",
    type: "string",
    required: false,
    choices: [],
    default: ""
  },
  {
    name: "uid",
    description: "FastGPT customUid.",
    type: "string",
    required: false,
    choices: [],
    default: "adh"
  }
]